### ISSUE TITLE
Robot_Toolkit: Pull all implemented objects Test_Script

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Robot_Toolkit#118] opened 2018-07-19 11:21 UTC
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment] 2020-01-07 14:51
This will be handled by general automated push-pull methods in Testing_Toolkit and with CI

**Comment by IsakNaslundBh** [comment] 2020-09-25 12:38
Closing as duplicate of https://github.com/BHoM/Robot_Toolkit/issues/155

**Closed by IsakNaslundBh** 2020-09-25 12:38 UTC
Labels: type:test-script
