### ISSUE TITLE
Robot_Toolkit: Push all implemented objects Test_Script

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Robot_Toolkit#117] opened 2018-07-19 11:20 UTC
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

**Comment by IsakNaslundBh** [comment] 2020-01-07 14:52
As https://github.com/BHoM/Robot_Toolkit/issues/118 this will be handled in Testing_Toolkit and with the general push-pull framework of the CI.

**Comment by IsakNaslundBh** [comment] 2020-09-25 12:37
Closing as duplicate of https://github.com/BHoM/Robot_Toolkit/issues/155

**Closed by IsakNaslundBh** 2020-09-25 12:37 UTC
Labels: type:test-script
