### ISSUE TITLE
Robot_Toolkit: Extracting Robot IDs from pulled elements no longer works

### ISSUE THREAD

**Issue by IsakLarbornBH** [BHoM/Robot_Toolkit#433] opened 2020-11-05 09:42 UTC
#### Description:

In the 3.3 versions, you can extract the Robot IDs of pulled elements from their `CustomData` parameter. while I am not sure exactly when this change occurred, this no longer works in the recent 4.0 versions.

#### Steps to reproduce:

Pull in elements, for example bars, from a Robot model. Explode the element, then Explode `CustomData`. In the 3.3 beta, you will find a parameter named `Robot_id`. In recent 4.0 alphas, you get nothing.

**Comment by IsakNaslundBh** [comment] 2020-11-06 13:22
This is not a bug, but an expected change.

Will need to post on teams about this, but was done as part of custom data removal from the code. The ID information can now be found in the fragments of the objects, rather than in the custom data.

https://github.com/BHoM/Robot_Toolkit/pull/429

Closing this issue, feel free to comment back if you disagree

**Closed by IsakNaslundBh** 2020-11-06 13:22 UTC
Labels: type:bug
